<?xml version="1.0" standalone="yes"?>
<!-- JDL Editor xml configuration file -->
<!--<!DOCTYPE edg:jdleconfig SYSTEM "file:jdleconfig.dtd">-->
<!--|edg:architectureAttName|edg:operatingSystemAttName|edg:versionAttName|edg:inboundAttName
	|edg:outboundAttName|specInt2000AttName|edg:specFloat2000AttName|edg:LRMSTypeAttName
	|edg:LRMSVersionAttName|edg:minMainMemoryAttName|edg:minMainMemoryAttName|edg:maxCPUTimeAttName
	|edg:estimatedTraversalTimeAttName|edg:runtimeEnvironmentAttName|edg:exprAttributeName
-->
<!DOCTYPE edg:jdleconfig [
  <!ELEMENT edg:jdleconfig (edg:attribute|edg:function|edg:replicacatalog|edg:dataaccessprotocol|edg:exprAttributeName)*>
  <!ELEMENT edg:attribute (edg:name, edg:type, edg:multi?)>
  <!ELEMENT edg:function (edg:name, edg:type, edg:params?)>
  <!ELEMENT edg:params (edg:type?, edg:type?, edg:type?)>
  <!ELEMENT edg:replicacatalog (#PCDATA)>
  <!ELEMENT edg:exprAttributeName (#PCDATA)>
  <!ELEMENT edg:dataaccessprotocol (#PCDATA)>
  <!ELEMENT edg:name (#PCDATA)>
  <!ELEMENT edg:type (edg:INTEGER|edg:FLOAT|edg:STRING|edg:BOOLEAN|
            edg:ABSTIME|edg:RELTIME|edg:MEMORY|edg:SECONDS|edg:LIST|
            edg:VALUE)>
  <!ELEMENT edg:multi EMPTY>
  <!ELEMENT edg:INTEGER EMPTY>
  <!ELEMENT edg:FLOAT EMPTY>
  <!ELEMENT edg:STRING EMPTY>
  <!ELEMENT edg:BOOLEAN EMPTY>
  <!ELEMENT edg:ABSTIME EMPTY>
  <!ELEMENT edg:RELTIME EMPTY>
  <!ELEMENT edg:MEMORY EMPTY>
  <!ELEMENT edg:SECONDS EMPTY>
  <!ELEMENT edg:LIST EMPTY>
  <!ELEMENT edg:VALUE EMPTY>

  <!ATTLIST edg:jdleconfig xmlns:edg CDATA #REQUIRED>

  <!-- Attributes for exprAttributeName tag (Requirements and Rank simple panels) -->
  <!ATTLIST edg:exprAttributeName architecture CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName OSType CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName OSVersion CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName OSTypeAndVersion CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName inbound CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName outbound CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName specInt2000 CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName specFloat2000 CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName LRMSType CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName LRMSVersion CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName minMainMemory CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName minNumberOfFreeCPUs CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName maxAvailableCPUTime CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName timeToTraverseQueue CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName runtimeEnvironment CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName maxNumberOfAvailableCPUs CDATA #IMPLIED>
  <!ATTLIST edg:exprAttributeName minNumberOfHandledJobs CDATA #IMPLIED>

  ]>

  <!--  OSTypeAndVersion = 'OpSys'
  -->
<edg:jdleconfig xmlns:edg='edg.workload.userinterface.gui'>
   <edg:exprAttributeName
        architecture = 'GlueHostArchitecturePlatformType'
        OSType = 'GlueHostOperatingSystemName'
        OSVersion = 'GlueHostOperatingSystemRelease'

        inbound = 'GlueHostNetworkAdapterInboundIP'
        outbound = 'GlueHostNetworkAdapterOutboundIP'
        specInt2000 = 'GlueHostBenchmarkSI00'
        specFloat2000 = 'GlueHostBenchmarkSF00'
        LRMSType = 'GlueCEInfoLRMSType'
        LRMSVersion = 'GlueCEInfoLRMSVersion'
        minMainMemory = 'GlueHostMainMemoryRAMSize'
        minNumberOfFreeCPUs = 'GlueCEStateFreeCPUs'
        maxAvailableCPUTime = 'GlueCEPolicyMaxCPUTime'
        timeToTraverseQueue = 'GlueCEStateEstimatedResponseTime'
        runtimeEnvironment = 'GlueHostApplicationSoftwareRunTimeEnvironment'
        maxNumberOfAvailableCPUs = 'GlueCEInfoTotalCPUs'
        minNumberOfHandledJobs = 'GlueCEStateTotalJobs'
   ></edg:exprAttributeName>

   <edg:replicacatalog>ldap</edg:replicacatalog>

   <edg:dataaccessprotocol>gridftp</edg:dataaccessprotocol>
   <edg:dataaccessprotocol>rfio</edg:dataaccessprotocol>
   <edg:dataaccessprotocol>file</edg:dataaccessprotocol>


   <!-- Attributes, add new attribute in alphabetical order. -->
   <edg:attribute>
	<edg:name>GlueCEHostingCluster</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>   
   <edg:attribute>
	<edg:name>GlueCEInfoGatekeeperPort</edg:name><edg:type><edg:INTEGER/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEInfoGRAMVersion</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEInfoHostName</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEInfoLRMSType</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEInfoLRMSVersion</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEInfoTotalCPUs</edg:name><edg:type><edg:INTEGER/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEName</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEPolicyMaxCPUTime</edg:name><edg:type><edg:SECONDS/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEPolicyMaxRunningJobs</edg:name><edg:type><edg:INTEGER/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEPolicyMaxTotalJobs</edg:name><edg:type><edg:INTEGER/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEPolicyMaxWallClockTime</edg:name><edg:type><edg:SECONDS/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEPolicyPriority</edg:name><edg:type><edg:BOOLEAN/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEStateEstimatedResponseTime</edg:name><edg:type><edg:SECONDS/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEStateFreeCPUs</edg:name><edg:type><edg:INTEGER/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEStateRunningJobs</edg:name><edg:type><edg:INTEGER/></edg:type>
   </edg:attribute>
   <edg:attribute>
    	<edg:name>GlueCEStateStatus</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEStateTotalJobs</edg:name><edg:type><edg:INTEGER/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEStateWaitingJobs</edg:name><edg:type><edg:INTEGER/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEStateWorstResponseTime</edg:name><edg:type><edg:SECONDS/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEStateWorstTraversalTime</edg:name><edg:type><edg:SECONDS/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueCEUniqueID</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostApplicationSoftwareRunTimeEnvironment</edg:name><edg:type><edg:STRING/></edg:type><edg:multi/>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostArchitecturePlatformType</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostArchitectureSMPSize</edg:name><edg:type><edg:INTEGER/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostBenchmarkSF00</edg:name><edg:type><edg:FLOAT/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostBenchmarkSI00</edg:name><edg:type><edg:INTEGER/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostMainMemoryRAMAvailable</edg:name><edg:type><edg:MEMORY/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostMainMemoryRAMSize</edg:name><edg:type><edg:MEMORY/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostMainMemoryVirtualAvailable</edg:name><edg:type><edg:MEMORY/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostMainMemoryVirtualSize</edg:name><edg:type><edg:MEMORY/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostName</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostNetworkAdapterInboundIP</edg:name><edg:type><edg:BOOLEAN/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostNetworkAdapterOutboundIP</edg:name><edg:type><edg:BOOLEAN/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostOperatingSystemName</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostOperatingSystemRelease</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostOperatingSystemVersion</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostProcessorCacheL1</edg:name><edg:type><edg:MEMORY/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostProcessorCacheL1D</edg:name><edg:type><edg:MEMORY/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostProcessorCacheL1I</edg:name><edg:type><edg:MEMORY/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostProcessorCacheL2</edg:name><edg:type><edg:MEMORY/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostProcessorClockSpeed</edg:name><edg:type><edg:FLOAT/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostProcessorInstructionSet</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostProcessorModel</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostProcessorOtherProcessorDescription</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostProcessorVendor</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostProcessorVersion</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>
   <edg:attribute>
	<edg:name>GlueHostUniqueID</edg:name><edg:type><edg:STRING/></edg:type>
   </edg:attribute>


   <!-- Functions, add new function in alphabetical order -->
   <edg:function>
	<edg:name>Ceil(F)</edg:name>
	<edg:type><edg:INTEGER/></edg:type>
	<edg:params>
	   <edg:type><edg:FLOAT/></edg:type>
	</edg:params>
   </edg:function>
   <edg:function>
	<edg:name>Floor(F)</edg:name>
	<edg:type><edg:INTEGER/></edg:type>
	<edg:params>
	   <edg:type><edg:FLOAT/></edg:type>
	</edg:params>
   </edg:function>
   <edg:function>
	<edg:name>IsMember(L, V)</edg:name>
	<edg:type><edg:BOOLEAN/></edg:type>
	<edg:params>
	   <edg:type><edg:LIST/></edg:type>
	   <edg:type><edg:VALUE/></edg:type>
	</edg:params>
   </edg:function>
   <edg:function>
	<edg:name>Member(L, V)</edg:name>
	<edg:type><edg:BOOLEAN/></edg:type>
	<edg:params>
	   <edg:type><edg:LIST/></edg:type>
           <edg:type><edg:VALUE/></edg:type>
           <!--<edg:type><edg:VALUE/></edg:type>-->
	</edg:params>
   </edg:function>
   <edg:function>
	<edg:name>RegExp(S, S)</edg:name>
	<edg:type><edg:BOOLEAN/></edg:type>
	<edg:params>
	   <edg:type><edg:STRING/></edg:type>
	   <edg:type><edg:STRING/></edg:type>
	</edg:params>
   </edg:function>
   <edg:function>
	<edg:name>Round(F)</edg:name>
	<edg:type><edg:INTEGER/></edg:type>
	<edg:params>
	   <edg:type><edg:FLOAT/></edg:type>
	</edg:params>
   </edg:function>
   <edg:function>
	<edg:name>StrCat(S, S)</edg:name>
	<edg:type><edg:STRING/></edg:type>
	<edg:params>
	   <edg:type><edg:STRING/></edg:type>
           <edg:type><edg:STRING/></edg:type>
	</edg:params>
   </edg:function>
   <edg:function>
	<edg:name>StrCat(S, S, S)</edg:name>
	<edg:type><edg:STRING/></edg:type>
	<edg:params>
	   <edg:type><edg:STRING/></edg:type>
	   <edg:type><edg:STRING/></edg:type>
           <edg:type><edg:STRING/></edg:type>
	</edg:params>
   </edg:function>
   <edg:function>
	<edg:name>SubStr(S, I)</edg:name>
	<edg:type><edg:STRING/></edg:type>
	<edg:params>
	   <edg:type><edg:STRING/></edg:type>
	   <edg:type><edg:INTEGER/></edg:type>
	</edg:params>
   </edg:function>
   <edg:function>
	<edg:name>SubStr(S, I, I)</edg:name>
	<edg:type><edg:STRING/></edg:type>
	<edg:params>
	   <edg:type><edg:STRING/></edg:type>
	   <edg:type><edg:INTEGER/></edg:type>
           <edg:type><edg:INTEGER/></edg:type>
	</edg:params>
   </edg:function>
   <edg:function>
	<edg:name>ToLower(S)</edg:name>
	<edg:type><edg:STRING/></edg:type>
	<edg:params>
	   <edg:type><edg:STRING/></edg:type>
	</edg:params>
   </edg:function>
   <edg:function>
	<edg:name>ToUpper(S)</edg:name>
	<edg:type><edg:STRING/></edg:type>
	<edg:params>
	   <edg:type><edg:STRING/></edg:type>
	</edg:params>
   </edg:function>
   
   
   <!-- To add after checking classad time functions format -->
   <!--<edg:function>
	<edg:name>CurrentTime()</edg:name>
	<edg:type><edg:ABSTIME/></edg:type>
   </edg:function>
   <edg:function>
	<edg:name>DayTime()</edg:name>
	<edg:type><edg:RELTIME/></edg:type>
   </edg:function>
   <edg:function>
	<edg:name>RelTime(S)</edg:name>
	<edg:type><edg:RELTIME/></edg:type>
	<edg:params>
          <edg:type><edg:SECONDS/></edg:type>
        </edg:params>
   </edg:function>-->
</edg:jdleconfig>










